spring:
  application:
    name: employee-attendance-report-batch
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_employee
    username: postgres
    password: postgres
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

app:
  attendanceClockIn: '08:30:00'
  attendanceClockOut: '17:30:00'
  startOvertimeHour: '19:30:00'
