spring:
  application:
    name: employee-attendance-report-batch
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_employee
    username: postgres
    password: postgres